import { createClient } from '@supabase/supabase-js';

export type SupabaseConfig = { url: string; anonKey: string };
export const supabaseConfig: SupabaseConfig | null = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY ? { url: import.meta.env.VITE_SUPABASE_URL.replace(/\/$/, ''), anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY } : null;
export const isSupabaseConfigured = Boolean(supabaseConfig);
export const supabase = supabaseConfig ? createClient(supabaseConfig.url, supabaseConfig.anonKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
export class SupabaseConnectionError extends Error { constructor(message = 'Supabase connection is not configured.') { super(message); this.name = 'SupabaseConnectionError'; } }
async function requestHeaders(extra: Record<string, string> = {}) { if (!supabaseConfig) throw new SupabaseConnectionError(); const result = supabase ? await supabase.auth.getSession() : { data: { session: null } }; return { apikey: supabaseConfig.anonKey, Authorization: `Bearer ${result.data.session?.access_token ?? supabaseConfig.anonKey}`, 'Content-Type': 'application/json', ...extra }; }
export async function supabaseFetch<T>(table: string, options: { method?: 'GET' | 'POST' | 'PATCH' | 'DELETE'; query?: string; body?: unknown; headers?: Record<string, string> } = {}): Promise<T> { if (!supabaseConfig) throw new SupabaseConnectionError(); const method = options.method ?? 'GET'; const response = await fetch(`${supabaseConfig.url}/rest/v1/${table}${options.query ?? ''}`, { method, headers: await requestHeaders({ ...(method === 'POST' || method === 'PATCH' ? { Prefer: 'return=representation' } : {}), ...options.headers }), body: options.body === undefined ? undefined : JSON.stringify(options.body) }); if (!response.ok) throw new Error((await response.text()) || `Supabase request failed with ${response.status}`); if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }
export async function signInWithPassword(email: string, password: string) { if (!supabase) throw new SupabaseConnectionError(); const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; return data; }
export async function uploadGalleryImage(path: string, file: File) { if (!supabase) throw new SupabaseConnectionError(); const { error } = await supabase.storage.from('gallery-images').upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; return { path, publicUrl: supabase.storage.from('gallery-images').getPublicUrl(path).data.publicUrl }; }
export async function removeGalleryImage(path: string) { if (!supabase) throw new SupabaseConnectionError(); const { error } = await supabase.storage.from('gallery-images').remove([path]); if (error) throw error; }
